# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_split_frequencies <- function(forest_object, max_depth) {
    .Call('_laserf_compute_split_frequencies', PACKAGE = 'laserf', forest_object, max_depth)
}

compute_weights <- function(forest_object, train_matrix, test_matrix, num_threads) {
    .Call('_laserf_compute_weights', PACKAGE = 'laserf', forest_object, train_matrix, test_matrix, num_threads)
}

compute_weights_oob <- function(forest_object, train_matrix, num_threads) {
    .Call('_laserf_compute_weights_oob', PACKAGE = 'laserf', forest_object, train_matrix, num_threads)
}

merge <- function(forest_objects) {
    .Call('_laserf_merge', PACKAGE = 'laserf', forest_objects)
}

subspace_forest_train <- function(train_matrix, outcome_index, split_rank, sample_weight_index, use_sample_weights, mtry, num_trees, min_node_size, sample_fraction, honesty, honesty_fraction, honesty_prune_leaves, alpha, imbalance_penalty, clusters, samples_per_cluster, compute_oob_predictions, num_threads, seed, legacy_seed) {
    .Call('_laserf_subspace_forest_train', PACKAGE = 'laserf', train_matrix, outcome_index, split_rank, sample_weight_index, use_sample_weights, mtry, num_trees, min_node_size, sample_fraction, honesty, honesty_fraction, honesty_prune_leaves, alpha, imbalance_penalty, clusters, samples_per_cluster, compute_oob_predictions, num_threads, seed, legacy_seed)
}

subspace_forest_predict <- function(forest_object, train_matrix, outcome_index, test_matrix, rank, num_threads) {
    .Call('_laserf_subspace_forest_predict', PACKAGE = 'laserf', forest_object, train_matrix, outcome_index, test_matrix, rank, num_threads)
}

subspace_forest_predict_oob <- function(forest_object, train_matrix, outcome_index, rank, num_threads) {
    .Call('_laserf_subspace_forest_predict_oob', PACKAGE = 'laserf', forest_object, train_matrix, outcome_index, rank, num_threads)
}

